function(enable_doxygen source_dir)
    option(ENABLE_DOXYGEN "Enable Doxygen for source builds" OFF)
    if(ENABLE_DOXYGEN)
        set(DOXYGEN_PROJECT_NAME "Alkahest Game Engine")
        set(DOXYGEN_GENERATE_HTML YES)
        set(DOXYGEN_GENERATE_TREEVIEW YES)
        set(DOXYGEN_DISABLE_INDEX YES)
        set(DOXYGEN_JAVADOC_AUTOBRIEF YES)
        set(DOXYGEN_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/docs)
        set(DOXYGEN_SHOW_USED_FILES NO)
        set(DOXYGEN_GENERATE_LATEX NO)
        set(DOXYGEN_RECURSIVE YES)
        set(DOXYGEN_VERBATIM_HEADERS NO)
        find_package(Doxygen)
        if (DOXYGEN_FOUND)
            doxygen_add_docs(doxygen-docs ${source_dir} ALL
                COMMENT "Generating API documenation with Doxygen...")
        else (DOXYGEN_FOUND)
            message("Doxygen needs to be installed to generate documentation!")
        endif()
    endif()
endfunction()
