function(enable_doxygen source_dir)
    option(ENABLE_DOXYGEN "Enable Doxygen for source builds" ON)
    if(CMAKE_BUILD_TYPE STREQUAL "Release")
        if(ENABLE_DOXYGEN)
            set(DOXYGEN_CALLER_GRAPH YES)
            set(DOXYGEN_CALL_GRAPH YES)
            set(DOXYGEN_DISABLE_INDEX YES)
            set(DOXYGEN_EXTRACT_ALL YES)
            set(DOXYGEN_GENERATE_TREEVIEW YES)
            set(DOXYGEN_JAVADOC_AUTOBRIEF YES)
            set(DOXYGEN_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/doc)
            set(DOXYGEN_SHOW_USED_FILES NO)
            find_package(Doxygen REQUIRED dot)
            doxygen_add_docs(doxygen-docs ${source_dir} ALL
                COMMENT "Generating API documentation with Doxygen...")

        endif()
    endif()
endfunction()
