macro(set_platform_detection_vars) 
    if(WIN32)
        message(STATUS "Target system is Windows, setting variables accordingly...")
        set(target_platform "windows")
        set(target_platform_include_macro "AKST_WIN32")
    elseif(APPLE)
        message(STATUS "Target system is Apple, setting variables accordingly...")
        set(target_platform "apple")
        set(target_platform_include_macro "AKST_APPLE")
    else()
        message(STATUS "Target system is Linux/Unix, setting variables accordingly...")
        set(target_platform "linux")
        set(target_platform_include_macro "AKST_LINUX")
    endif()
endmacro()
