macro(set_platform_detection_vars) 
    if(WIN32)
        message(STATUS "Target system is Windows, setting variables accordingly...")
        set(target_platform "windows")
    elseif(APPLE)
        message(STATUS "Target system is Apple, setting variables accordingly...")
        set(target_platform "apple")
    else()
        message(STATUS "Target system is Linux/Unix, setting variables accordingly...")
        set(target_platform "linux")
    endif()
endmacro()
