#!/bin/bash

if [ -z "$1" ]; then
    BUILD_TYPE=Debug
else
    BUILD_TYPE=$1
fi

cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_EXPORT_COMPILE_COMMANDS=YES -Bbuild -S.

if [ ! -f "./compile_commands.json" ]; then
    ln -s build/compile_commands.json .
fi

cmake --build build
